#!/bin/bash
#echo 'Hello, World!'
#read -rp 'Your Login: ' login_name
#echo "login $login_name" > creds
#read -rsp 'Your password: ' password && echo
#echo "password $password" >> creds

#tag=git describe
tag=1.0.dsfjdkfhkhf
#echo $tag
#echo $tag | awk -F '.' '{print $3}'
#echo $tag | awk -F '.' '{print $1"."$2"."$3+1}'
#newtag=$(echo $tag | awk -F '.' 'BEGIN {print "new tag is:"} {print $1"."$2"."$3+1}')
#echo $tag
#echo $newtag 

#length=${#tag}
#echo $length

#$ true && echo hello   
if [ ${#tag} > 5 ]
then
   echo yes
   a+=1
   echo 'new iteration is' $a
   newtag=$(echo $tag | awk -F '.' 'BEGIN {print "new tag is:"} {print $1"."$2"."$3+'$a'}')
   echo $newtag
else 
   echo no changes
fi

